"""Add users, chat_rooms, and messages tables

Revision ID: 28a7c49f31ac
Revises: fe314fbf7184
Create Date: 2025-01-22 09:46:33.352147

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28a7c49f31ac'
down_revision: Union[str, None] = 'fe314fbf7184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['userId'])
    op.create_foreign_key(None, 'chat_messages', 'chat_rooms', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###